server:
  port: 9191
# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

# Connection url for the database w/createDatabaseIfNotExist=true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: root
    password: 
    #initialization-mode: always
  jpa:
    generate-ddl: true
    open-in-view: true #transaction
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false 
resource_id:
  product_api: product_api
